name: Update Sail-To-Lean

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Sail
        run: |
          sudo apt install opam
          git clone git@github.com:rems-project/sail.git
          cd sail
          make install

      - name: Run a one-line script
        run: echo Hello, world!
