name: Update Sail-To-Lean

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install APT
        run: |
          sudo apt install build-essential libgmp-dev z3 cvc4 cmake
          sudo apt install opam ocaml-dune menhir

      - name: Install OPAM
        run: |
          opam init --yes --no-setup --shell=sh

      - name: Clone Sail
        run: |
          git clone https://github.com/rems-project/sail.git

      - name: Install Sail Dependences
        run: |
          opam install sail --deps-only

      - name: Build and Install Sail
        run: |
          (cd sail ; dune build --release)
          (cd sail ; dune install)


      - name: Install RISCV
        run: |
          git clone https://github.com/RaitoBezarius/sail-riscv.git
          cd sail-riscv
          git checkout lean
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build/ --target generated_lean_rv64d_lean

